### PR TITLE
New function, code refactor and docs update

### PR DESCRIPTION
**Pull request by SimonLeclere**

### CODE REVIEW

**Comment by tutyamxx** [comment]
Thanks for the contribution but you added unnecessary things such as linter. For a 6 lines module.

**Comment by SimonLeclere** [comment]
I think it's important, even on a small module of 6 lines, to have a code readable by all :) It's a habit I've got into.

**Comment by tutyamxx** [comment]
Not disagreeing at all, but the code is already readable by anyone. 

Also, to back up my statement why I think it is not really needed, is because everyone have different linter options set up (and there are too many files to be downloaded by npm anyway). Also, refractoring a code is fine, as long as the developer respects my choice of coding style and variable wording.

**Comment by SimonLeclere** [comment]
Fine I respect that choice, do you want me to remove the .eslintrc.json file from my pull request?

**Comment by tutyamxx** [comment]
Up to you.

**Comment by SimonLeclere** [comment]
Done :)

**Pull request closed without merging**
